### PR TITLE
Fixes #8 Adds Sample Files for AV testing and Cleans up Repository

### LINKED ISSUE #8: Problem: Need a file over 20mb with a virus for testing
There are 4 scenarios to effectively test clamAV:

1) files < 20M that have virus  WE HAVE
2) files < 20M that don’t have virus WE HAVE
3) files > 20 M that have virus WE DO NOT HAVE
4) files > 20M that don’t have virus WE HAVE

We need a file that is over 20mb that has a virus.

### PR DESCRIPTION
**Pull request by ross-spencer**
Sample files with viruses to satisfy https://github.com/artefactual/archivematica-sampledata/issues/8.

Closes #8.

### CODE REVIEW

**Comment by sevein** [comment]
Would be useful to add a file or two without viruses?

**Comment by sevein** [comment]
Nitpicks:
- I think it's good practice to squash the commit history once the PR is ready for CR. More about this here: https://github.com/artefactual/archivematica/blob/stable/1.6.x/CONTRIBUTING.md#commit-history. It would probably be enough with a single commit.
- Don't end the summary line of a commit with a period because it's a title - see https://github.com/erlang/otp/wiki/Writing-good-commit-messages.
- The title of the PR is not meaningful - just the name of the branch.

Forgive me please! 😅

**Review by sevein — CHANGES_REQUESTED** [review]
I've added a few suggestions :)

**Comment by jhsimpson** [comment]
@sevein  this comment: 
The title of the PR is not meaningful - just the name of the branch.

why not have a meaningful title in the PR?  I guess if the pr links to issues that define the problem, then the PR name is less important?

**Comment by sevein** [comment]
> why not have a meaningful title in the PR?

I was suggesting to have one that serves a summary of the solution - instead of just letting GH name it automatically after the name of the branch.

> I guess if the pr links to issues that define the problem, then the PR name is less important?

Well yeah until someone submits an issue like "Problem: 502 gateway timeout" and the solution is "Introduce a job queue". I think the solution always deserves a summary line. @ross-spencer added one but it's in the description of the PR - that wasn't obvious when I was looking at this PR from the PR list page.

If you submit a PR that has a single commit, GH automatically uses the subject line of the commit message to title the PR.

`</nitpick>`

**Comment by ross-spencer** [comment]
@sevein @jhsimpson I've added the two extra files and updated the documentation. I'm having trouble with the rebase to squish the commits. It seems to have included (but not changed) the commit you made in October Justin:

     commit 8af45ef4193df1bc4627d8243ba726dc78cd4c28 (HEAD -> dev/issue-8-fileover20mb-with-virus, 
     origin/dev/issue-8-fileover20mb-with-virus)
     Author: Ross Spencer <all.along.the.watchtower2001@gmail.com>
     Date:   Fri Nov 10 15:19:39 2017 +1300

         Antivirus test files and repository cleanup

     commit 1f3ca90c7c012c027a5116aec8edce68f5400054
     Author: Justin Simpson <jsimpson@artefactual.com>
     Date:   Sun Oct 15 22:38:52 2017 -0700

         updating OPF format corpus

There doesn't seem to be any harm reviewing the code - but can you see a problem? Any advice how to fix it up appreciated. There's a little bit of getting used to the GitHub process I need to do.

**Review by sevein — CHANGES_REQUESTED** [review]
I've noticed that you've pushed this branch to GitHub. Ask someone in #operations to add your key to our private git server because that's where we need to push it instead. Once they're done I think you can follow this script to bring this branch back to normality and clean up the history:

```shell
$ cd archivematica-sampledata                                  # Enter in your git local repo
$ git remote set-url origin git@git.artefactual.com            # Redefine the URL of the remote
$ git checkout dev/issue-8-fileover20mb-with-virus             # Make sure you're working tree is in this branch
$ git rebase master                                            # Your branch deviated and we lost master's HEAD, let's take it back
$ git reset --soft HEAD~2                                      # Destroy your commits, move its changes to the staged area
$ git status -s                                                # Verify that the changes are now in the staged area
$ git commit -m "Antivirus test files and repository cleanup"  # Commit the changes
$ git push -f                                                  # Rewrite the remote branch
```

The part of the script where we change the remote to git@git.artefactual.com is necessary for all the repos under the artefactual organization.

This is a good link: https://github.com/k88hudson/git-flight-rules - it may help next time.

**Comment by ross-spencer** [comment]
Thanks again Jesús. That's all good. Hopefully this one can be reviewed and merged now.

**Review by sevein — APPROVED** [review]
👍

**Pull request merged**
