### PR TITLE
Adds sample data for testing Bulk Extractor

### PR DESCRIPTION
**Pull request by ross-spencer**
Adds various files to test AM bulk extractor capability for credit card numbers and social security numbers. 

Additional data has been added to test against the full bulk extractor suite. The data will generate positive matches against bulk_extractor1.5.5 and can potentially be used add these features to Archivematica in the future.

### CODE REVIEW

**Comment by sallain** [comment]
In the README I'd suggest indicating which scanners are run - @sromkey thinks that Archivematica runs them all, but it would be good to confirm.

Otherwise, LGTM!

**Comment by sromkey** [comment]
This is a great addition to the test transfers, thank you! If we confirm that we are running all the scanners we could continue adding more to the samples as time allows.

**Comment by ross-spencer** [comment]
@sallain @sromkey I've updated the README.md to reflect the state of knowledge having tested Sarah's thought's this morning. Should be looking good but let me know!

**Review by sallain — APPROVED** [review]
Looks good! We should add some of this information to the docs, too.

**Comment by ross-spencer** [comment]
Aces! Thank you both! :+1:

**Comment by ross-spencer** [comment]
Closes #17

**Pull request merged**
