### PR TITLE
Update checksum examples to work with Hashsum 

### PR DESCRIPTION
**Pull request by ross-spencer**
This commit updates the sample data to be compatible with checksum
verification changes in Archivematica 1.10.

For examples demonstrating multiple checksum algorithms additional
checksums have been added to match the new capability of the system,
for example, SHA512 and BLAKE2 chacksum files have been added.

Where we are demonstrating the failure conditions I have tried to
engineer a failure for each of the checksum types. Failures may
include missing files, and invalid, or incorrect checksums. The goal
is for the microservice job to tell us this!

In the final few changes here, individual checksum files have been
updated so they continue to work with the microservice. The virus
scanning checksum file is a good example.

Connected to archivematica/issues#346
Related to https://github.com/artefactual/archivematica/pull/1333

### CODE REVIEW

**Comment by sallain** [comment]
Oh neat, thanks @ross-spencer! I didn't realize that SHA-512 and BLAKE2 were on the way!

**Review by sallain — APPROVED** [review]
I don't have a qa/1.x site to test these on but the structure and method seem sound to me - and if they don't work, it'll come out through testing 😸

**Comment by ross-spencer** [comment]
SHA512 and Blake2 all incidental @sallain but I'm excited! Thanks for the quick review!

**Comment by ross-spencer** [comment]
Hi @sallain can you just confirm this late addition as well? I somehow missed it previously (probably because it fails, but for different reasons) https://github.com/artefactual/archivematica-sampledata/pull/54/commits/d3ab518fd7c6de8d00f928d04654b12fed76df31 once confirmed I'll get the merge done prior to `1.10` testing (soon!).

**Review by sallain — APPROVED** [review]

**Pull request merged**
