### PR TITLE
Remove extraneous bytes from eicar test file

### PR DESCRIPTION
**Pull request by ross-spencer**
Connected to archivematica/issues#1137

### CODE REVIEW

**Review by sarah-mason — CHANGES_REQUESTED** [review]
That works now! 
```
$ clamscan --max-filesize 32M *
README.md: OK
metadata/checksum.md5: OK
test.1M.eicar.with-virus: Win.Test.EICAR_HDB-1 FOUND
test.1M.nukem.with-virus: Win.Trojan.Nukem-1 FOUND
test.1M.null.no-virus: OK
test.30M.eicar.with-virus: OK
test.30M.nukem.with-virus: Win.Trojan.Nukem-1 FOUND
test.30M.null.no-virus: OK
test.zero.byte.no-virus: Empty file
test.zip.eicar.with-virus.zip: Win.Test.EICAR_HDB-1 FOUND
```

BUT...

`test.30M.eicar.with-virus` is still coming up incorrect though. Do we need a sample 30M for the eicar test file? Could we then just remove it instead of trying to alter it? Based on your previous tests there appears to be a limit to the file size. If we remove it, we should also just update the README and checksum file.

And speaking of checksum files, the `checksum.md5` needs updating now that the file has changed. It failed _Verify metadata directory checksums_ when I tried to put it through Archivematica. Just some small changes to do. A huge thank you for investigating and getting a working test file for future tests though!

**Comment by ross-spencer** [comment]
> test.30M.eicar.with-virus is still coming up incorrect though. Do we need a sample 30M for the eicar test file? Could we then just remove it instead of trying to alter it? Based on your previous tests there appears to be a limit to the file size. If we remove it, we should also just update the README and checksum file.

> And speaking of checksum files, the checksum.md5 needs updating now that the file has changed. It failed Verify metadata directory checksums when I tried to put it through Archivematica. Just some small changes to do. A huge thank you for investigating and getting a working test file for future tests though!

Doh :man_facepalming:!  of course! I'll get those sorted.

**Comment by ross-spencer** [comment]
@sarah-mason would you give it another whirl? Should be good to go! :crossed_fingers:

**Review by sarah-mason — APPROVED** [review]
It worked

**Pull request merged**
