### PR TITLE
Adds comprehensive transfer for demonstrations

### PR DESCRIPTION
**Pull request by sallain**
This transfer includes several formats, meaningful descriptive metadata,
submission documentation, rights, checksums, and dummy credit card and
social security numbers. It's intended to be used for demonstrating
Archivematica functionality to prospective users. It works well with AtoM
DIP upload.

### CODE REVIEW

**Comment by sromkey** [comment]
This looks great. Things I checked when testing (everything passed):
- rights and dc correctly in METS
- bulk extractor reports for pii exist
- submission docs and metadata files recorded in METS
- AIP will store, DIP will upload to AtoM.
The only thing I can think to add would be an image with text for OCR but I don't think that's crucial.

**Review by sromkey — APPROVED** [review]

**Comment by sallain** [comment]
@romkey thanks! Yeah, adding an OCR-able image would be good. I'll merge this for now and add that when I have time.

**Comment by kellyannewithane** [comment]
@sallain @sromkey this is great!  that mp4 file is a pretty huge though when normalized.  should we keep it out?

**Comment by sromkey** [comment]
It depends I guess on whether you think of this as a tool for demonstrations or for testing. I think it's super useful for testing purposes, but I'd probably continue to use smaller transfers for demos.

**Comment by sallain** [comment]
I envision this as being used for demos. I think I'll replace the mp4 with a smaller video, though. It takes way too long to normalize and to download the AIP.

**Comment by kellyannewithane** [comment]
Makes sense.  I like that it has All the Things for demoing .

**Pull request merged**
