### PR TITLE
adds rightsTransfer sample data

### PR DESCRIPTION
**Pull request by sarah-mason**
When updating the Metadata Import documentation, there was a rightsTransfer test being used, but no sample data existed to create the PREMIS rights events. I recreated the transfer and am now adding it to the sample data to make future updates to the docs easier.

loosely related to issue: https://github.com/archivematica/Issues/issues/949 -- though this was about updating the METS schema, it included PREMIS schema updates.

### CODE REVIEW

**Review by ross-spencer — COMMENTED** [review]
I like this @sarah-mason. I feel it's a good use of the TestTransfers folder too. 

There are two small things, I'd like to consider before merging, one that might be fixed, and one that I'm not sure about an approach for:

1. Can you modify the detailed commit message to `72` characters per line? Per our [style guide](https://github.com/archivematica/Issues/issues/1181). Let me know if you need a hand at all.

2. The note: `Note about license.` doesn't appear in the final METS. I haven't consulted the PREMIS standard but I am guessing `premis:LicenseNote` isn't a thing where `premis:CopyrightNote` is? But I wonder what would be a good thing to do? I guess verify that in the PREMIS standard, and if so, maybe log an issue about the extent of support for this in Archivematica? or perhaps, keep the field blank? What do you think?

**Comment by sromkey** [comment]
`licenseNote` is in PREMIS! See 4.1.4.3 in the [v. 3.0 data dictionary](http://www.loc.gov/standards/premis/v3/premis-3-0-final.pdf)

**Comment by ross-spencer** [comment]
Ruh-roh! thanks @sromkey In that case (I can get this from the code if I need I guess!) but are you anticipating it works in AM at present? Or is it an enhancement we'd need to make?

**Comment by sarah-mason** [comment]
@ross-spencer -- it should include the license note. It did when I was making the[ docs update](https://www.archivematica.org/en/docs/archivematica-1.11/user-manual/transfer/import-metadata/#rights-csv). I'm going to test it again on my vm now.

I also tried to fix my git commit message, so hopefully it worked. But if not, let me know what I should be doing. I suspect I should try to update nano to see if I can at least get some soft wrapping in there.

**Comment by sromkey** [comment]
> @ross-spencer -- it should include the license note. It did when I was making the[ docs update](https://www.archivematica.org/en/docs/archivematica-1.11/user-manual/transfer/import-metadata/#rights-csv). I'm going to test it again on my vm now.

What @sarah-mason said! It should work!

**Comment by ross-spencer** [comment]
OK!

**Comment by sarah-mason** [comment]
Confirmed: I am still getting the `<premis:licenseNote>migrate</premis:licenseNote>` for the first rightsMD section.

Did I fix the commit message okay?

**Comment by ross-spencer** [comment]
@sarah-mason @sromkey (unhelpfully) I crossed my wires -- Sarah M - you have a string in the csv under citation. The string is `Note about license`. This is what isn't appearing in the METS. Is that important at all? Same question about archivematica/PREMIS support etc.

I think you might need to push the new commit :slightly_smiling_face: -- you may need to `git push -f`

**Comment by sarah-mason** [comment]
@ross-spencer -- you are right that `citation` is only used when `statute` is used, not `copyright` or `license`. It's 4.1.5.2 in the data dictionary. I will amend it and then update the docs as well.

**Review by ross-spencer — APPROVED** [review]
This is really cool, thanks for putting it together Sarah. 

There's one tiny thing which you might choose to fix, and then go ahead and merge, (i.e. no need to wait for further approval) which is a small typo, in the `doc_id_role`: `Statte documentation identifier role`. Otherwise. all is good.

**Comment by sarah-mason** [comment]
have done just that! Thanks Ross.

**Pull request merged**
