### PR TITLE
Create logical separation of Bag samples in Bag examples dir

### PR DESCRIPTION
**Pull request by ross-spencer**
This PR creates a separate bag transfer directory with examples of current bags so that all combinations can be tested, and the test suite can be easily added to. 

The primary two benefits of this PR are:

* Adds reference examples of Bag Transfers with CSV metadata.
* Adds `tar.gz` transfer support which we should support: [here](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/transfer/bags/#zipped-bags)

Chatting to Sara, this PR creates some short-term duplication where AMAUAT is still tightly coupled with other Bag sample data still in the repository. I have proposed we remove this post-1.11 testing where our reliance on AMAUAT is lessened for a short while. 

The new layout is as follows:
```
SampleTransfers/BagExamples$ $ tree -d
.
├── TarGzBags
├── UnzippedBags
│   ├── BaggedDemoTransferCSV
│   │   ├── data
│   │   │   └── artwork
│   │   └── metadata
│   │       └── submissionDocumentation
│   ├── BagTransfer
│   │   └── data
│   │       └── bagTest
│   ├── SimpleBagWithProcessingMCP
│   │   └── data
│   └── UnzippedBag
│       └── data
└── ZippedBags
```

Connected to archivematica/Issues#771
Connected to archivematica/Issues#851
Connected to https://github.com/archivematica/Issues/issues/859

Closes https://github.com/artefactual/archivematica-sampledata/pull/66

### CODE REVIEW

**Comment by ross-spencer** [comment]
Fixed up following https://github.com/archivematica/Issues/issues/1123 `tar.gz` files will work in `qa/1.x`

**Review by sarah-mason — APPROVED** [review]
Looks good, Ross! I very much appreciate the organisation of these transfers and the duplication between unzipped and zipped bags. Have you thought about adding detail to the README.MD to just add a bit about what the different sample sets are good for? (not necessary, just wondered)

**Comment by ross-spencer** [comment]
Thanks @sarah-mason. I usually try to, I also had them in the original PR for this but then removed them as I couldn't make them clear enough. But I think it's true now that the purpose of each could be made much clearer in README and I have a clearer picture of that. I can address this later in the week, but if you think this PR will also improve the regression testing experience up-front then we can merge and I can come back to it after that too.

**Comment by sarah-mason** [comment]
@ross-spencer - I think it will probably sped up regression testing and you are busy this week, so I would say go ahead and merge it. Then come back to the README when you have a little bit more time to think about it. This really meets my need for organisation! 😄

**Comment by ross-spencer** [comment]
Alright! Merging, and placing the note to add README at the top of my list for the moment I have some down-time.

Thank you Sarah! 🙇

**Pull request merged**
